apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events-web
  name: events-web-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: events-web
      ver: v2.0
  template:
    metadata:
      labels:
        app: events-web
        ver: v2.0
    spec:
      containers:
      - image: samdatta93/events-website-cp:v4.0
        name: events-web
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: SERVER
          value: "http://events-api-svc:8082" 
